{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "erp",
  "main": "index.ts",
  "compatibility_date": "2025-12-22",
  "observability": {
    "enabled": true
  },

  // Add this to your wrangler.jsonc
  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "a9f5a98afbd64b90a73dc81b02c339d0",
      
      // Optional: preview_id used when running `wrangler dev` for local dev
      "preview_id": "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"
    }
  ]
}
