name = "material-flow-pro"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat_v2"]

# Pages 配置
pages_build_output_dir = "dist"

[observability]
enabled = true

# KV 命名空间绑定
[[kv_namespaces]]
binding = "erp"
id = "a9f5a98afbd64b90a73dc81b02c339d0"
# preview_id 用于本地开发环境，请替换为您的预览 KV 命名空间 ID
preview_id = "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"
